# Generated by Django 2.2.28 on 2024-03-22 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_rating',
            options={'verbose_name_plural': 'Book Ratings'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='book_rating',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='movie_rating',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='book_rating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='movie_rating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='book_rating',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Book'),
        ),
        migrations.AlterField(
            model_name='book_rating',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie_rating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
