# Generated by Django 2.2.28 on 2024-03-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_rating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='movie_rating',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='book_rating',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Book'),
        ),
        migrations.AlterField(
            model_name='book_rating',
            name='rating',
            field=models.IntegerField(max_length=5),
        ),
        migrations.AlterField(
            model_name='movie_rating',
            name='rating',
            field=models.IntegerField(max_length=5),
        ),
    ]
