# Generated by Django 2.2.28 on 2024-03-21 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_rating',
            options={'verbose_name_plural': 'Book Ratings'},
        ),
        migrations.AlterModelOptions(
            name='movie_rating',
            options={'verbose_name_plural': 'Movie Ratings'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.RemoveField(
            model_name='book_rating',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='movie_rating',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='book_rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie_rating',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book_rating',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rate.Book'),
        ),
    ]
