# Generated by Django 2.2.28 on 2024-03-22 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20240322_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
