# Generated by Django 2.2.28 on 2024-03-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20240319_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_rating',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='movie_rating',
            name='user_id',
        ),
    ]
