# Generated by Django 2.2.28 on 2024-03-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20240321_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_rating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie_rating',
            name='user',
        ),
        migrations.AlterField(
            model_name='book',
            name='picture',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
