# Generated by Django 2.2.28 on 2024-03-20 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0002_auto_20240319_1652'),
        ('rate', '0003_auto_20240320_1130'),
    ]

    operations = [
    ]
