# Generated by Django 2.2.28 on 2024-03-20 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_merge_20240320_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_rating',
            options={'verbose_name_plural': 'Book Ratings'},
        ),
        migrations.AlterModelOptions(
            name='movie_rating',
            options={'verbose_name_plural': 'Movie Ratings'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
    ]
