# Generated by Django 2.2.28 on 2024-03-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0005_auto_20240320_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_title',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='book_rating',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie_rating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
