# Generated by Django 2.2.28 on 2024-03-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0006_auto_20240321_1621'),
        ('rate', '0006_auto_20240321_1220'),
    ]

    operations = [
    ]
