# Generated by Django 2.2.28 on 2024-03-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0007_merge_20240321_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_rating',
            name='rating',
            field=models.IntegerField(max_length=1),
        ),
    ]
