# Generated by Django 2.2.28 on 2024-03-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0008_auto_20240321_1801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='book_title',
        ),
    ]
