# Generated by Django 2.2.28 on 2024-03-21 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0003_auto_20240321_0835'),
        ('rate', '0009_auto_20240321_1836'),
    ]

    operations = [
    ]
