# Generated by Django 2.2.28 on 2024-03-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0010_merge_20240321_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie_rating',
            options={},
        ),
    ]
